### ISSUE TITLE
Questions about mean result?

### ISSUE THREAD

**Issue by WangJun-ZJUT** [Ghostish/Open3DSOT#34]
Dear authors,

Thanks for your work, I suffer from a question when following your work. 

The paper reports result for multi-category and reports a mean result. 

I wonder if the result for per-category is obtained by training the model on the data of the specified category.

Thanks!

**Comment by Ghostish** [comment]
> I wonder if the result for per-category is obtained by training the model on the data of the specified category.

Yes, we follow previous works to train and evaluate the tracker per category.  And the reported "mean" result is the weighted sum of the per-category results according to the number of frames.

**Comment by WangJun-ZJUT** [comment]
Hi! I got it. thanks for your reply and I will close this issue soon.
