### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by suyzhi** [Ghostish/Open3DSOT#35]
Hello author, why am I having this problem when reproducing the code?
I'd appreciate it if you could help me.

**Comment by Ghostish** [comment]
It could be related to the dataset. Seems that your data is damaged and thus the number of points within object bb is always zeros. Please make sure your dataset is correctly set up.

**Comment by suyzhi** [comment]
I use the KITTI dataset download from your github link. Also，I took training out of "data_tracking_velodyne.zip" and put it in folder.I uploaded the layout of the KITTI dataset, could you please check it for me.
[check.zip](https://github.com/Ghostish/Open3DSOT/files/9188884/check.zip)

**Comment by suyzhi** [comment]
<img width="340" alt="微信截图_20220726195642" src="https://user-images.githubusercontent.com/99389990/181000288-43708a47-07cc-41eb-a9e0-aec896e059a3.png">

**Comment by Ghostish** [comment]
Could you show more details of the error message?  Have you visualized your data to make sure that they are not corrupted?

**Comment by suyzhi** [comment]
No, not yet.Could you teach me how to visualize this data?I don't know how to open these bin files.
![微信图片_20220727115455](https://user-images.githubusercontent.com/99389990/181158289-ee0dbcad-44f0-4739-b857-52aab50a3f25.jpg)

**Comment by suyzhi** [comment]
![Uploading 微信图片_20220727115455.jpg…]()

**Comment by suyzhi** [comment]
![微信图片_20220727115455](https://user-images.githubusercontent.com/99389990/181160161-4e780394-7009-4dbf-bf8b-0bc4c2d2f53a.jpg)

**Comment by suyzhi** [comment]
There seems to be nothing wrong with visualizing the data.
<img width="1280" alt="微信截图_20220727123216" src="https://user-images.githubusercontent.com/99389990/181162157-ca75e642-7bc2-4647-854b-6a43183cb875.png">

**Comment by suyzhi** [comment]
There seems to be nothing wrong with visualizing the data.
<img width="1280" alt="contrast" src="https://user-images.githubusercontent.com/99389990/181174537-e839db7a-33d0-45c4-ac98-808a336b11a3.png">

**Comment by suyzhi** [comment]
After downloading your code, I found such a problem, I need to modify seg_label and motion_state_label to long type, and when using cross entropy, I will fall into the problem o
<img width="1280" alt="error" src="https://user-images.githubusercontent.com/99389990/181193073-226cb390-43e7-43e9-aed7-aec3f287dcee.png">
f too deep recursion, how can I solve this problem?

**Comment by suyzhi** [comment]
After downloading your code, I found such a problem, I need to modify seg_label and motion_state_label to long type, and when using cross entropy, I will fall into the problem of too deep recursion, how can I solve this problem?
<img width="1280" alt="error" src="https://user-images.githubusercontent.com/99389990/181193213-f37faf4c-9e7f-4061-8915-3035cc311a6e.png">
