### ISSUE TITLE
Hi author, can you kindly provide a direct copy of pre-trained NuScenes model?

### ISSUE THREAD

**Issue by Xiaoqiong-Liu** [Ghostish/Open3DSOT#36]
Congratulation on the great work of M2Track.
In the paper, there's comparison of P2B, BAT, and M2Track on the NuScenes in 5 categories.  Can you kindly release all 15 trained model? Thank you!

**Comment by Ghostish** [comment]
Including all 15 trained models may heavily burden our repo.  We suggest that you train the models from scratch since the results are not hard to reproduce.

**Comment by Xiaoqiong-Liu** [comment]
Any suggestion for the training setting of NuScenes, like batch size(256 or 50 for Car?) and epoch(how many for Nuscenes) will be appreciated.
I tried to train a P2B NuScenes tracker given the repository but found it is very time-consuming, and result in an error at last.
Not sure if I did something wrong or have an improper configuration.

**Comment by Ghostish** [comment]
Hi there. For your reference, we train the models using 4 Titan 3080ti and we set the batch size as large as possible to fully utilize the GPU memories (e.g., batch size =64/GPU for $M^2$-Track). And the epoch is all set to 60.

**Comment by Xiaoqiong-Liu** [comment]
Thank you very much for the information,  I will follow this suggestion. BTW, may I know how long it takes for training 60 epochs on NuScenes in your environment?

**Comment by Ghostish** [comment]
For $M^2$-Track, it takes about 20～30 mins per epoch on 4 3080Tis with `--preloading` set.

**Comment by Xiaoqiong-Liu** [comment]
Thanks, I will have a try.
