### ISSUE TITLE
How to do the visualization of result?

### ISSUE THREAD

**Issue by suyzhi** [Ghostish/Open3DSOT#37]
Hello,author.Could you tell me how to visualize the result as video or gif? I am looking forward to your reply!

**Comment by suyzhi** [comment]
Thank you for your reply! I would like to know more about how to generate this animation result, and I wonder if you have a simple solution.

**Comment by Ghostish** [comment]
To be more specific, I save the 8 corners of a bbox in a specific order and draw lines between corresponding corner pairs to show the bbox. Actually, there are no technical difficulties to do visualization.  I am not going to release the visualization code because it is messy.

**Comment by suyzhi** [comment]
Thank you for your patient answer, I will try to do it.
