### ISSUE TITLE
BAT配置中的use_search_feature问题

### ISSUE THREAD

**Issue by li199603** [Ghostish/Open3DSOT#45]
你好，我发现在BAT的所有配置文件里use_search_feature都被设置为False
但是在论文中的3.4.2节却表示使用了search_feature（the extracted feature of the corresponding search point）
请问是设置为False更好吗？或者是我哪里理解错了

**Comment by Ghostish** [comment]
Indeed, you are correct. The search features are primarily utilized for BoxCloud prediction and comparison purposes. Interestingly, we have discovered that removing the search features during concatenation does not negatively impact performance but actually improves the speed of the process.
